### ISSUE TITLE
CallWrapper override does not seem to work

### ISSUE THREAD

**Issue by chapmanjacobd** [trin5tensa/tkinter_exception_handling#1]
https://github.com/trin5tensa/tkinter_exception_handling/blob/f403181e99ca4da176f35afd47cb40d33a9dd501/4_override_call_wrapper.py#L81

This works for me:

```
from tkinter import Tk

def callback_error(self, *args):
    raise Exception(*args)
Tk.report_callback_exception = callback_error
```

**Comment by trin5tensa** [comment]
Thank you for your contribution. The stack trace looks much better.. 

I’ve changed and renamed 4_override_call_wrapper to 4_override_report_exception. I prefer a bare `raise`. It avoids the appearance that two distinct exceptions have been enchanted and it maintains the complete stack trace starting with `sys.exit(main())`.

I’ve also updated 5_model_solution although there I subclassed Tk instead of monkey patching `report_callback_exception`.
